version: '3.8'

services:
  postgres:
    image: postgres:16.2-alpine
    container_name: Postgres
    restart: unless-stopped
    env_file:
      - .env  # Especifica la ubicación del archivo .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

volumes:
  postgres_data:
